---
- hosts: all
  tasks:
  - name: Create the filders /tmp/dirXY with XY from 1 to 10
    file: 
      dest: '/tmp/dir{{ item }}'
      state: directory
    with_sequence: start=1 end=10
    become: true